"""empty message

Revision ID: 0882d7619f94
Revises: c75335442491
Create Date: 2019-09-26 16:55:51.793226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0882d7619f94'
down_revision = 'c75335442491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flora_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('collection_lot', sa.String(), nullable=True),
    sa.Column('analysis_lot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['flora_id'], ['flora.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed')
    # ### end Alembic commands ###
