"""empty message

Revision ID: 4a096826d2d1
Revises: a9bb05e762c1
Create Date: 2019-09-15 05:04:08.747659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a096826d2d1'
down_revision = 'a9bb05e762c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flora', sa.Column('germination_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flora', 'germination_code')
    # ### end Alembic commands ###
