"""empty message

Revision ID: 7553308242c0
Revises: de6261f5169a
Create Date: 2019-10-06 07:43:07.556360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7553308242c0'
down_revision = 'de6261f5169a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flora', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flora', 'name')
    # ### end Alembic commands ###
