"""empty message

Revision ID: b3f4314bb732
Revises: ffed846ae3be
Create Date: 2019-10-12 12:22:57.619343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f4314bb732'
down_revision = 'ffed846ae3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seed', sa.Column('analysis_date', sa.Date(), nullable=True))
    op.add_column('seed', sa.Column('collection_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seed', 'collection_date')
    op.drop_column('seed', 'analysis_date')
    # ### end Alembic commands ###
