"""empty message

Revision ID: c75335442491
Revises: e99461399b6d
Create Date: 2019-09-25 17:03:35.591025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75335442491'
down_revision = 'e99461399b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fauna', sa.Column('sub_species', sa.String(), nullable=True))
    op.add_column('fauna', sa.Column('variety', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fauna', 'variety')
    op.drop_column('fauna', 'sub_species')
    # ### end Alembic commands ###
