"""empty message

Revision ID: e99461399b6d
Revises: d43c9f5c8c34
Create Date: 2019-09-25 05:39:17.040087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99461399b6d'
down_revision = 'd43c9f5c8c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_locations',
    sa.Column('flora_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flora_id'], ['flora.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('flora_id', 'location_id')
    )
    op.add_column('location', sa.Column('altitude', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'altitude')
    op.drop_table('plant_locations')
    # ### end Alembic commands ###
