"""empty message

Revision ID: ffed846ae3be
Revises: 7553308242c0
Create Date: 2019-10-06 10:24:47.859268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffed846ae3be'
down_revision = '7553308242c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fauna', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fauna', 'name')
    # ### end Alembic commands ###
